### Class 10 

## Numpy indexing and selection

In [1]:
import numpy as np


In [2]:
a =np.arange(0,11)
#show array

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#get a value at an index [8]
a[8]

8

In [4]:
a[1:5]

array([1, 2, 3, 4])

### Broad casting , setting up value with index range

In [10]:
a[0:5]= 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# rest array
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# SLICING THE RANGE
slice_a=a[0:6]
slice_a

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_a[:]=99      # changed who slice range to 99 , because : means from start to end
slice_a

array([99, 99, 99, 99, 99, 99])

In [18]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
# data is not copied , it is  a nthe orginal array this avoids memeory problems

In [20]:
a_copy = a.copy()
a_copy 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Explicitly tell to copy the array , otherwise changing variable is just same as original 

In [21]:
ab= a_copy

In [22]:
ab

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
ab[:]=0

In [24]:
ab

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
a_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Indexing a 2D array(matrices)

In [26]:
# the general format is arry_2d[row][col]  or arr_2d[row,col]

In [27]:
b =np.array(([5,10,15],[20,25,30],[35,40,45]))

b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
# indexing row
b[0]
b[0][1]
b[1][0]

20

In [31]:
b[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
# bottom row ,h last number
b[2][2]

45

In [39]:
# bottom left
b[:][:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
b[1:,:2]

array([[20, 25],
       [35, 40]])

### Fancy Indexing

In [45]:
#set up matrix
d=np.zeros((10,10))
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
d.shape

(10, 10)

In [53]:
# For i in range

for i in range(10):
    d[i]=i
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [54]:
# FANCY INDEXING

In [61]:
d[[2,4,6,8]]


array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [65]:
# SELECTION OF ELEMENTS
a = np.arange(1,11)
a
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
bool_a= a>4
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])