In [1]:
## class 18 linear algebra

In [2]:
import  numpy as np

In [3]:
v= np.array([1,2,3,4])

In [4]:
v

array([1, 2, 3, 4])

In [8]:
# matrix of 2-3 elements

m=np.array([[1,2,3],[4,3,2]])
m

array([[1, 2, 3],
       [4, 3, 2]])

In [10]:
t=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
import numpy as np

# create a 3x3x3 tensor
tensor_3d = np.array([
                    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
                    ])

# print the tensor
print(tensor_3d)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [16]:
v1=np.array([5,7,9])
v2=np.array([2,3,5])


In [17]:
v1*2

array([10, 14, 18])

In [18]:
np.dot(v1,v2)

76

In [19]:
v1+v2

array([ 7, 10, 14])

In [20]:
v1-v2

array([3, 4, 4])

In [21]:
i=np.identity(3,dtype=int)

In [27]:
a=np.random.randint(5,size=(3,3))
b
b=np.random.randint(5,size=(3,3))
b

array([[2, 3, 1],
       [0, 3, 3],
       [4, 1, 2]])

In [28]:
a*b

array([[ 6,  6,  0],
       [ 0, 12,  3],
       [ 8,  0,  4]])

In [30]:
m=np.matmul(a,b)
m

array([[ 6, 15,  9],
       [ 6, 16, 15],
       [12,  8,  6]])

In [31]:
m.T

array([[ 6,  6, 12],
       [15, 16,  8],
       [ 9, 15,  6]])

In [32]:
ev, evs=

SyntaxError: invalid syntax (799361707.py, line 1)

In [33]:
inv=np.linalg.inv(m)
inv

array([[-0.03333333, -0.025     ,  0.1125    ],
       [ 0.2       , -0.1       , -0.05      ],
       [-0.2       ,  0.18333333,  0.00833333]])

In [1]:
import statistics as st
data = [32,34,65,45,57,567,7,54,54,34,355,4,43,4,3423,34,223,33,2,2765,34]

st.mean(data)

374.7142857142857

In [2]:
st.meadia(data)

AttributeError: module 'statistics' has no attribute 'meadian'