### Class 10 

## Numpy indexing and selection

In [1]:
import numpy as np


In [2]:
a =np.arange(0,11)
#show array

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#get a value at an index [8]
a[8]

8

In [4]:
a[1:5]

array([1, 2, 3, 4])

### Broad casting , setting up value with index range

In [10]:
a[0:5]= 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# rest array
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# SLICING THE RANGE
slice_a=a[0:6]
slice_a

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_a[:]=99      # changed who slice range to 99 , because : means from start to end
slice_a

array([99, 99, 99, 99, 99, 99])

In [18]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
# data is not copied , it is  a nthe orginal array this avoids memeory problems

In [20]:
a_copy = a.copy()
a_copy 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Explicitly tell to copy the array , otherwise changing variable is just same as original 

In [21]:
ab= a_copy

In [22]:
ab

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
ab[:]=0

In [24]:
ab

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
a_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Indexing a 2D array(matrices)

In [26]:
# the general format is arry_2d[row][col]  or arr_2d[row,col]

In [27]:
b =np.array(([5,10,15],[20,25,30],[35,40,45]))

b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
# indexing row
b[0]
b[0][1]
b[1][0]

20

In [31]:
b[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
# bottom row ,h last number
b[2][2]

45

In [39]:
# bottom left
b[:][:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
b[1:,:2]

array([[20, 25],
       [35, 40]])

### Fancy Indexing

In [45]:
#set up matrix
d=np.zeros((10,10))
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
d.shape

(10, 10)

In [53]:
# For i in range

for i in range(10):
    d[i]=i
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [54]:
# FANCY INDEXING

In [61]:
d[[2,4,6,8]]


array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [65]:
# SELECTION OF ELEMENTS
a = np.arange(1,11)
a
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
bool_a= a>4
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [96]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
a+a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [98]:
a*a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [100]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
a/a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [106]:
a%a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [107]:
a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

## universal array functions

In [108]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [109]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [110]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [111]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [112]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [114]:
# Adission

a=np.array([10,42,18,80])
b=np.array([8,30,10,50])

c=np.add(a,b)

c

array([ 18,  72,  28, 130])

In [115]:
d = np.subtract(a,b)
d

array([ 2, 12,  8, 30])

In [117]:
e=np.multiply(a,b)
e

array([  80, 1260,  180, 4000])

In [119]:
# division
g=np.divide(a,b)
g

array([1.25, 1.4 , 1.8 , 1.6 ])

In [124]:
p=np.power(a,)
p

array([    100, 3111696,     324,  512000], dtype=int32)

In [125]:
# variance
np.var(b)


290.75

In [160]:
m=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
am=np.array(m)
am

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [161]:
k=np.sum(m)
k

78

In [162]:
k=np.sum(m,axis=0)
k

array([22, 26, 30])

In [163]:
q=a[a>2]

## finding elements based on condition

In [166]:
b=np.arange(0,10)
c=np.arange(11,20)

In [187]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([0.36788141, 0.02969423, 0.09883745, 0.19503201, 0.6693161 ,
       0.38636864, 0.40302546, 0.97707356, 0.71319527, 0.60644537,
       0.77161779, 0.16063594, 0.12892013, 0.6476733 , 0.31678239,
       0.58316798, 0.59039603, 0.15668283, 0.49070667, 0.30610762,
       0.01577842, 0.89500389, 0.16320314, 0.91259725, 0.46892762])

In [229]:
x=np.arange(0.01,1.01,0.01)
x
y=x.reshape(10,10)
y

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [279]:
x=np.arange(12,26)
new=np.delete(x,(4,9))
new.reshape((3,4))

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [280]:
print("20")

20


In [284]:
x=np.array([2,7,12]).reshape(3,1)
x

array([[ 2],
       [ 7],
       [12]])

In [288]:
x=np.arange(21,26)
x

array([21, 22, 23, 24, 25])

In [303]:
x=np.arange(16,30)
x

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [304]:
x


array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [305]:
np.sum(x)

315

In [312]:
x

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [313]:
x.std()

4.031128874149275

In [323]:
x=np.arange(0,100)
s=np.sum(x)
x = x/s*325
x
np.sum(x)

325.0

In [328]:
x=np.arange(10)
x
st=np.std(x)


2.8722813232690143

In [329]:
array([55, 60, 65, 70, 75])

NameError: name 'array' is not defined

In [349]:
x=np.arange(1,100)
x_sum=np.sum(x)
x/x_sum*

4950

In [361]:
x=np.arange(0,100)
s=np.sum(x)
x = x/s*325
x
s=np.sum(x,axis=0)
x[:,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed