# CLASS 8
## ERROR

In [3]:
Exception handlings

# try and accept block

try:
    you do your operations here...
    
    except ExceptionI, then execute this block.
    
    except

SyntaxError: invalid syntax (997090424.py, line 1)

In [4]:
f = open('testfile','w')
f.write('test write this')
f.close()



In [5]:

try:
    f = open('testfile','r')
    f.read()

except:
    #this will only check for an io error exception and then execute this 
    print("error: could not find file or read data")
else:
    print("content reading done")
    f.close()

content reading done


In [6]:
try:
    f = open("testfile","w")
    f.write("hello, i created this file yo")
    f.close()
finally:
    print("always execute this block of code damn it")

always execute this block of code damn it


In [7]:
def ask_int_value():
    try:
        val = int(input("enter interger value"))
        print(val)
    except:
        print("add only integer value")
        val = int(input("enter interger value"))
    finally:
        print("finally , i executed !")
        print(val)
        
        
ask_int_value()

add only integer value
enter interger value13
finally , i executed !
13


In [ ]:
while True:
    try:
        val=int(input("enter the input value"))
    except:
        print("looks like you entered wrong value")
        continue
    else:
        print("yes this is an integer")
        
    finally:
        print("code is executed")
    print(val)
    

enter the input value13
yes this is an integer
code is executed
13
enter the input value13
yes this is an integer
code is executed
13
enter the input value2
yes this is an integer
code is executed
2


In [ ]:
while True:
    try:
        val = int(input("enter your digit"))
    except:
        print("LOOKS LIKE YOU DID NOT ENTER INTEGER")
        continue
    else:
        if val in range(10, 15):
            print("yep thats an integer!")
            print(val)
            break

    finally:
        print("code has run properly")


# Python PIP

### PIP STANDS FOR  PACKAGE INSTALLER FOR PYTHON

In [5]:
pip--version

pip 21.2.4 from C:\ProgramData\Anaconda3\lib\site-packages\pip (python 3.9)

Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:


import numpy as np

l= [1,2,3]
l
np.array(l)

array([1, 2, 3])

In [8]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)




array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [11]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(10 )

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random function of numpy ... gives random array

In [16]:
np.random.randn(5,5)

array([[ 0.80441988, -1.46409277,  1.72738972,  0.85060017, -1.16631189],
       [ 0.59701625, -0.30688529,  0.61906048,  0.31992608,  0.29175693],
       [ 0.68853309, -1.58447829,  0.4392393 ,  2.19247707,  0.78387058],
       [-1.74584237, -1.17655844, -1.96932815,  0.24891949, -1.82379935],
       [-1.25978467,  0.81651658,  0.81953027, -2.15049357, -1.33739695]])

In [17]:
np.random.rand(5,5)

array([[0.99597402, 0.40029339, 0.59843618, 0.19101935, 0.42993958],
       [0.9668987 , 0.87163769, 0.97751786, 0.20656442, 0.35742555],
       [0.70481532, 0.56452616, 0.2519979 , 0.35151532, 0.6029701 ],
       [0.4284198 , 0.18614546, 0.63009171, 0.66186337, 0.36485578],
       [0.42329806, 0.28706331, 0.24696741, 0.87589414, 0.55288838]])

In [18]:
np.random.randn(6)

array([-0.02646673,  0.46123298, -0.4134279 , -0.30566309,  0.06393832,
       -2.12344293])

## RAND INT

np.random.rand

In [19]:
np.random.randint(1,100,10)

array([99, 16, 68, 14, 35, 56, 39, 14, 47, 97])

In [20]:
np.random.rand(3,4,3)

array([[[0.96463799, 0.81290413, 0.8266971 ],
        [0.01266194, 0.85399287, 0.06420225],
        [0.29630712, 0.44724367, 0.24313811],
        [0.89877851, 0.06677899, 0.13385152]],

       [[0.06259155, 0.20373395, 0.15483939],
        [0.01123279, 0.19246234, 0.33411928],
        [0.59525338, 0.24631355, 0.5737157 ],
        [0.16569942, 0.82652857, 0.19999627]],

       [[0.30061677, 0.61578893, 0.53187905],
        [0.70650883, 0.04068338, 0.35391657],
        [0.43597679, 0.10243948, 0.07209973],
        [0.02609567, 0.28648702, 0.52732256]]])

In [21]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
arr.max()

23

In [23]:
arr.min()

0

In [24]:
arr.argmax()

23

In [25]:
arr.argmin()

0

In [26]:
#reshape
arr.shape

(24,)

In [27]:
narr =arr.reshape(6,4)
narr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# D type
### you  can also grab the data type of the object in the array

In [28]:

arr.dtype

dtype('int32')

In [31]:
x =(np.empty((3,4),dtype=int))
print(x)

[[  719691453 -1080354280  1399969904  1071482071]
 [ 1277221386 -1076202086  -346537409 -1076654085]
 [ -162821432  1068523074 -1511352660 -1073677105]]


In [32]:
y=(np.full((33),55))
y= 

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [33]:
y=np.bincount(x).max()

ValueError: object too deep for desired array

In [48]:
x=[4,18,2,8,3,15,20,12,6,3,15,12,131,19,14,81,23,44]
x=np.array(x)
x.max()
np.bincount(x)

array([0, 0, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 2, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [62]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,6,6])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 6])

In [63]:
arr1.max()

9

In [64]:
np.argmax(arr1)


8

In [65]:
np.bincount(arr1)

array([0, 1, 1, 1, 1, 1, 3, 1, 1, 1], dtype=int64)

In [71]:
k =np.bincount(arr1)
s= argmax(k)

NameError: name 'argmax' is not defined